// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kxkqcsxysbcdkveolnrf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt4a3Fjc3h5c2JjZGt2ZW9sbnJmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwNzI1MTMsImV4cCI6MjA2ODY0ODUxM30.HWjiVSf3pmWCUZebZeTjqAggi3cxw-CZQTZIlTTBPbk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});